### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by miwakos** [miwakos/furima-36089#12]
# アプリURL
https://furima-36089.herokuapp.com/
# Basic認証
- ID
admin
- Password
36089
# 出品者用アカウント
- email
testa@test.com
- password
test123
# 購入者用アカウント
- email
testb@test.com
- password
test123

**Comment by snkw-works** [comment]
@miwakos さん、大変お待たせいたしました。ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/126093707-9b1b375d-18e4-4320-9540-aa4a4781adec.png)
